### PR TITLE
Stop aligning imports

### PR DESCRIPTION
**Pull request by jsteiner**
Alignment makes adding and deleting imports cumbersome to maintain.
Better to just leave them unaligned.

### CODE REVIEW

**Comment by sidraval** [comment]
I like to align the package names, but not align the imports as such:

```
import qualified Web.Scotty as S
import           Data.Aeson (decode)
```

Up to you!

Either way, :+1:

**Comment by jferris** [comment]
My major complaint with all vertical alignment is that it results in mass-restyling or inconsistency.

@sidraval in your example, do you leave room for the `qualified` keyword even when there are no qualified imports? If so, you'd have code like this:

``` haskell
import           Control.Monad (void)
import           Data.Aeson (decode)
```

If not, you'd get diffs like this:

``` diff
- import Control.Monad (void)
- import Data.Aeson (decode)
+ import           Control.Monad (void)
+ import           Data.Aeson (decode)
+ import qualified Web.Scotty as S
```

**Comment by sidraval** [comment]
Yeah, I leave room for the `qualified` keyword, even if there are no qualified imports. Agree that it makes dirty diffs, but it makes scanning the imports easier for me.

**Comment by jferris** [comment]
I like the import formatting we specify in the [guides](https://github.com/thoughtbot/guides/tree/master/style/haskell):

> Order imports in three sections, separating each by a blank line: standard libraries, third-party libraries, application modules. Within each section, alphabetize the imports and place qualified imports last.

``` haskell
import Control.Monad.State (state, evalState)
import Data.List (foldl')
import Data.Text (Text)
import qualified Data.Map  as M
import qualified Data.Text as T

import Database.Persistent (runSql)
import Yesod
import Yesod.Auth (requireAuthId, maybeAuthId)

import Foundation
import Settings
```

**Pull request merged**
